name: 'marketing_project'
version: '1.0.0'
config-version: 2

profile: 'default'
model-paths: ["marketing_project/models"]
analysis-paths: ["marketing_project/analyses"]
macro-paths: ["marketing_project/macros"]
test-paths: ["marketing_project/tests"]

models:
  marketing_project:
    staging:
      +materialized: view
    prep:
      +materialized: view
    mart:
      +materialized: table
